version: "3.2"
services:

  clickhouse:
    image: yandex/clickhouse-server:latest
    # build:
    #     context: .
    #     dockerfile: clickhouse.Dockerfile
    #     cache_from:
    #         - yandex/clickhouse-server:latest
    container_name: clickhouse-server 
    ports:
        - "8123:8123"
    volumes:
        -  ./db/ch_db:/var/lib/clickhouse
        # Base Clickhouse cfg
        # - ./config/config.xml:/etc/clickhouse-server/config.xml
        # - ./config/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
        - clickhouse
    restart: always

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: tabix
    ports:
        - "8124:80"
    networks:
        - clickhouse
    depends_on:
        - clickhouse
    restart: always
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      CH_NAME: clickhouse
      CH_HOST: clickhouse:8123 

  grafana:
    image: qxip/clickhouse-grafana
    container_name: grafana
    ports:
     - "3005:3000"
    volumes:
      - ./db/grf:/var/lib/grafana
    networks:
        - clickhouse
    depends_on:
        - clickhouse
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: ${USER}
      GF_SECURITY_ADMIN_PASSWORD: ${PASSWORD}

networks:
    clickhouse:
    
volumes:
    clickhouse:
    grafana: